name: 'Terraform Dev Plan/Apply'

on:
  push:
    branches:
      - main
jobs:
  dev:
    name: 'Terraform Dev 2 Plan/Apply'
    uses: yorkutest/templates/.github/workflows/tf-plan-apply_env.yml@main
    with:
      storageAccountInfo: ${{ vars.TF_STORAGE_ACCOUNT_INFO }}
      deploymentType: 'Create'
      commandOptions: '-var-file=variables/dev.tfvars'
      storageKey: 'projectName/dev/test_rg.tfstate'
      target-env: development
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
