name: 'Terraform Dev Deploy'

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  unit-tests:
    name: 'Terraform Unit Tests'
    uses: yorkutest/templates/.github/workflows/tf-unit-tests.yml@release/v0.3

  deploy_dev:
    name: 'Deploy to development'
    uses: yorkutest/templates/.github/workflows/tf-plan-apply_env.yml@release/v0.3
    needs: [unit-tests]
    permissions:
      id-token: write
      contents: read
    with:
      storageAccountInfo: ${{ vars.TF_STORAGE_ACCOUNT_INFO }}
      deploymentType: 'Create'
      commandOptions: '-var-file=variables/development.tfvars'
      storageKey: 'projectName/dev/test_rg.tfstate'
      target-env: development
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
