name: 'Terraform Configuration Drift Detection'

on:
  workflow_dispatch: 
  schedule:
    - cron: '41 3 * * *' # runs nightly at 3:41 am

jobs:
  call-workflow:
    name: 'Terraform Configuration Drift Detection'
    permissions:
      issues: write
      id-token: write
      contents: read
    uses: yorkutest/templates/.github/workflows/tf-drift.yml@release/v0.3
    with:
      storage-key: 'projectName/stage/test_rg.tfstate'
      storage-account-info: ${{ vars.TF_STORAGE_ACCOUNT_INFO }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
