name: 'Terraform provisioning'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy_dev:
    name: 'Deploy to development'
    uses: yorkutest/templates/.github/workflows/tf-plan-apply_env.yml@main
    with:
      storageAccountInfo: ${{ vars.TF_STORAGE_ACCOUNT_INFO }}
      deploymentType: 'Create'
      commandOptions: '-var-file=variables/development.tfvars'
      storageKey: 'projectName/dev/test_rg.tfstate'
      target-env: development
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
