name: 'Terraform Dev Deploy'

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  unit-tests:
    name: 'Terraform Unit Tests'
    uses: yorkutest/templates/.github/workflows/tf-unit-tests.yml@main

  deploy_dev:
    name: 'Deploy to development'
    uses: yorkutest/templates/.github/workflows/tf-plan-apply_env.yml@main
    needs: [unit-tests]
    with:
      storageAccountInfo: ${{ vars.TF_STORAGE_ACCOUNT_INFO }}
      deploymentType: 'Create'
      commandOptions: '-var-file=variables/development.tfvars'
      storageKey: 'dev/testrg/rg.tfstate'
      targetEnv: development
    secrets: inherit
#      token: ${{ secrets.GITHUB_TOKEN }}

