name: 'Terraform Stage and Prod Deployment'

on:
  push:
    tags:
       - 'release/*'

jobs:
  deploy_stage:
    name: 'Deploy to staging'
    uses: yorkutest/templates/.github/workflows/tf-plan-apply_env.yml@v0.1
    with:
      storageAccountInfo: ${{ vars.TF_STORAGE_ACCOUNT_INFO }}
      deploymentType: 'Create'
      commandOptions: '-var-file=variables/stage.tfvars'
      storageKey: 'projectName/stage/test_rg.tfstate'
      target-env: stage
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  deploy_production:
    name: 'Deploy to production'
    needs: deploy_stage
    uses: yorkutest/templates/.github/workflows/tf-plan-apply_env.yml@v0.1
    with:
      storageAccountInfo: ${{ vars.TF_STORAGE_ACCOUNT_INFO }}
      deploymentType: 'Create'
      commandOptions: '-var-file=variables/production.tfvars'
      storageKey: 'projectName/production/test_rg.tfstate'
      target-env: production
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
