name: 'Terraform Stage and Prod Deployment'

on:
  push:
    tags:
       - 'release/*'

permissions:
  id-token: write
  contents: read
      
jobs:
  unit-tests:
    name: 'Terraform Unit Tests'
    uses: yorkutest/templates/.github/workflows/tf-unit-tests.yml@main

  deploy_stage:
    name: 'Deploy to staging'
    uses: yorkutest/templates/.github/workflows/tf-plan-apply_env.yml@main
    needs: [unit-tests]
    with:
      storageAccountInfo: ${{ vars.TF_STORAGE_ACCOUNT_INFO }}
      deploymentType: 'Create'
      commandOptions: '-var-file=variables/stage.tfvars'
      storageKey: 'stage/testrg/rg.tfstate'
      targetEnv: stage
    secrets: inherit
#      token: ${{ secrets.GITHUB_TOKEN }}

  deploy_production:
    name: 'Deploy to production'
    needs: deploy_stage
    uses: yorkutest/templates/.github/workflows/tf-plan-apply_env.yml@main
    with:
      storageAccountInfo: ${{ vars.TF_STORAGE_ACCOUNT_INFO }}
      deploymentType: 'Create'
      commandOptions: '-var-file=variables/production.tfvars'
      storageKey: 'production/testrg/rg.tfstate'
      targetEnv: production
    secrets: inherit
#      token: ${{ secrets.GITHUB_TOKEN }}
