name: 'Terraform Unit Tests'

on:
#  pull_request:
#    branches:
#      - main
  push:


jobs:
  unit-tests:
    name: 'Terraform Unit Tests'
    uses: yorkutest/templates/.github/workflows/tf-unit-tests.yml@main
  dev-plan:
    name: 'Terraform Dev Plan'
    needs: [unit-tests]
    uses: yorkutest/templates/.github/workflows/tf-plan-apply_env.yml@main
    with:
      storageAccountInfo: ${{ vars.TF_STORAGE_ACCOUNT_INFO }}
      deploymentType: 'Plan'
      commandOptions: '-var-file=variables/development.tfvars'
      storageKey: 'projectName/dev/test_rg.tfstate'
      target-env: development
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
